includes:
- ./classification.yaml
- configs/datasets/propaganda/bert.yaml

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

optimizer:
  type: adam_w
  params:
    lr: 1e-5
    eps: 1e-8

evaluation:
    metrics:
    - multilabel_micro_f1
    - multilabel_macro_f1

training:
  batch_size: 16
  lr_scheduler: true
  max_updates: 16000
  early_stop:
    criteria: propaganda/roc_auc
    minimize: false

checkpoint:
  pretrained_state_mapping:
    bert: bert
